# Generated by Django 3.1.7 on 2021-03-22 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True, verbose_name='Nome Receita')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes')),
                ('modo_preparo', models.TextField(verbose_name='Modo Preparo')),
                ('tempo_preparo', models.IntegerField(verbose_name='Tempo Preparo')),
                ('redimento', models.CharField(max_length=100, verbose_name='Rendimento')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('data_receita', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
