# Generated by Django 3.1.7 on 2021-03-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_auto_20210322_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
